services:
  app:
    image: changedan/coffeetime:latest
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DISCORD_WEBHOOK=${DISCORD_WEBHOOK}
      - ISSUER=${ISSUER}
      - SECRET=${SECRET}
      - ACCESS_TOKEN_TIME=${ACCESS_TOKEN_TIME}
      - REFRESH_TOKEN_TIME=${REFRESH_TOKEN_TIME}