services:
  app:
    image: changedan/coffeetime:latest
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - spring_profiles_active=prod
      - DB_HOST=${DB_HOST}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DISCORD_WEBHOOK=${DISCORD_WEBHOOK}
      - ISSUER=${ISSUER}
      - SECRET=${SECRET}
      - ACCESS_TOKEN_TIME=${ACCESS_TOKEN_TIME}
      - REFRESH_TOKEN_TIME=${REFRESH_TOKEN_TIME}
      - OCI_NAMESPACE=${OCI_NAMESPACE}
      - OCI_BUCKET=${OCI_BUCKET}
      - OCI_REGION=${OCI_REGION}
      - OCI_ACCESS_KEY=${OCI_ACCESS_KEY}
      - OCI_SECRET_KEY=${OCI_SECRET_KEY}