services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: changedan/coffeetime:latest
    container_name: coffeetime_container
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: "dev"
    env_file:
      - .env