# build stage
FROM openjdk:17-jdk-slim AS build

# install
RUN apt-get update && apt-get install -y --no-install-recommends \
    wget \
    unzip \
  && rm -rf /var/lib/apt/lists/*

# gradle
ARG GRADLE_VERSION=7.6
RUN wget https://services.gradle.org/distributions/gradle-${GRADLE_VERSION}-bin.zip \
    && unzip gradle-${GRADLE_VERSION}-bin.zip -d /opt/ \
    && ln -s /opt/gradle-${GRADLE_VERSION}/bin/gradle /usr/bin/gradle \
    && rm gradle-${GRADLE_VERSION}-bin.zip

# working dir
WORKDIR /app

# copy
COPY gradlew gradlew.bat /app/
COPY gradle /app/gradle
COPY build.gradle settings.gradle /app/

# cache gradle
RUN ./gradlew dependencies --no-daemon

# copy
COPY src /app/src

# build
RUN ./gradlew clean build -x test --no-daemon

# runtime stage
FROM openjdk:17-jdk-slim

# working dir
WORKDIR /app

# copy
COPY src/main/resources/application*.yml /app/

# copy
COPY --from=build /app/build/libs/*.jar coffeetime.jar

# port
EXPOSE 8080

# entrypoint
ENTRYPOINT ["java",  "-jar", "-Duser.timezone=Asia/Seoul", "coffeetime.jar"]