spring:
  config:
    activate:
      on-profile: "prod"
  datasource:
    url: ${DB_HOST}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
